### ISSUE TITLE
Is this a "study"?

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#25]
_I did not understand how the study was done and why. There is clearly a lack of details here and I am not even sure if this is a proper study in particular:_
 
- I am not convinced by the rationale behind the choice of shapes “some of these shapes were derived from common table shapes which could be used with tabletop interfaces, such as the semi-circle design.” I would suggest trying to cite here 31 or 32 who present more rationale behind choice of shapes and may help explain why those are interesting.
- The study section need restructuring: explain what is the goal aimed in this study first and have traditional subsections with participants / apparatus / tasks etc. Would be also good to state at the beginning (and intro what type of study is done, here a qualitative / observational study done in order to xxx).
- A figure of each applications of the study would be good
- Why choosing those applications? it seems that there is a hidden goal from the authors to test whether the content is randomly placed and the impact of layout but this is stated nowhere. E.g. it would be great to have some hypothesis of why you think those differences will impact the way user interact and to validate/invalidate them through the results.
- Lack of detail about the study, what did the participants done exactly? where the app randomized? the shape? what is being observed, how did you observed it (cameras recording participants?) how many participants and their demography. How did you analyze the observation (transcription?)
- Unclear what did we learn from the study at all, especially because it is unclear what they are searching at first. In the end, this paper shows a new algorithm but I have no proof that it does actually rearrange the UIs in an efficient way for users and thus this does not really strengthen the motivation for an automatic reconfiguration

**Comment by jamcnaughton** [comment]
- I feel our justification is stronger than just copying 31 and 32 as the shapes were chosen by an expert (i.e. the furniture designer) as being desirable in their industry.
- **Re-structuring paper to be more of a position piece focusing on the presentation and implications of the DSDIs through observations on their implementation.**
- **I can add an image with each of the applications in.**
- **Explain applications chosen from those available in the SynergyNet framework. Drop any discussion of 'randomly position content' with the algorithm and refer to it as content whose layout has no significance (because it is random).**
- As this will become a discussion of an implementation instead of a study no additional detail should be required.
- Again, not a study so nothing to learn other than the qualitative information in the form of observations on, and subsequent discussions of its implementation.

**Comment by jamcnaughton** [comment]
Resolved in commit 5b91bd7.
