### ISSUE TITLE
Highlight novelty of DSDI approach

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#28]
_The DSDIs are interesting. Authors should indicate whether these issues are totally novel or whether they have already been identified in the past (and cite references). I can think of other issues, in particular legibility and aesthetics. For instance rotating content may not affect any of the identified DSDIs, but may significantly affect the legibility of the content. I understand that authors identified issues directly related to the visual properties, but maybe they should consider other categories of issues (such as usability, perception, etc.)._

**Comment by jamcnaughton** [comment]
- Make it clear the DSDIs are derived from first-hand observations and nothing else.
- Rotating content is not an issue because tabletop interfaces are by definition horizontal. 
- Need to clearly state scope of the technique (i.e. visual content layout) - but state future work could involve further investigation of other issues like usability and readability.

**Comment by jamcnaughton** [comment]
Resolved in commit 25f6a47.
