### ISSUE TITLE
Validation of approach

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#4]
The authors conclude their paper with a long discussion of how their technique could be used or implemented. Results are illustrated only for very simple image compositions. But how does your algorithm work with more complex examples? How does it compare to other layout algorithms? I am missing a proper validation of the proposed technique. Although this research topic is very promising, it seems like this project is still at an early stage and requires a number of revisions before being ready for publication.  

Also, a user study could reveal how layout adaptations affect the usability of such an application.

**Comment by jamcnaughton** [comment]
Again, a mock up of legacy software could be useful in responding to this.

I did actually carry out a study but its pretty basic. I basically cut out shapes (deemed to be likely desirable designs by a professional furniture designer), put them on a large desktop, loading up several SynergyNet apps and applied the algorithm to the shape. I don't know if its worth mentioning this in the paper due to its simplicity.

I have a few photos of it which I could add.

**Comment by jamcnaughton** [comment]
![research 09](https://cloud.githubusercontent.com/assets/1144661/25456320/76e91a16-2aca-11e7-8a14-aef090d5a6f4.jpg)
![research 11](https://cloud.githubusercontent.com/assets/1144661/25456319/76e72d14-2aca-11e7-9df2-e42d6af56ee1.jpg)

**Comment by jamcnaughton** [comment]
Mostly fixed already as there is dicussion of the study in the paper.

Renaming the implementation section to 'Study' and the discussions section to 'Observations' should make this clearer.  The addition of photos from the study and the prototypes above should also help resolve this issue.

**Comment by jamcnaughton** [comment]
Renamed sections and added photos.
