### ISSUE TITLE
Other technical layout challenges

### ISSUE THREAD

**Issue by tomcrick** [tomcrick/HCCIS2017-DSDI#5]
Finally, irregularly shaped display outlines and the resulting cropping of rectangular content are by far not the only layout challenges arising when dealing with tabletop displays. Reduced content visibility by steep viewing angles (see Wigdor et al., CHI 2007), rotation ambiguity when multiple users are collaborating around a tabletop (e.g., Kruger et al., CSCW 2004), privacy issues (see, e.g., Scott et al., ECSCW 2003), and occlusion by physical objects (e.g., Vogel and Balakrishnan, CHI 2010) are not addressed by the proposed technique.

**Comment by jamcnaughton** [comment]
I think we'll have to make clear that the focus of this article is adaption to the shape, not to a tabletop display - the software is already expected to be suited to the display being used in every way except the shape.

We could make the paper's scope wider and rather than discussing the algorithm in regards to tabletop displays discuss it in regards to displays in general - I'd originally intended for this but my co-authors thought this made the scope way too big.

**Comment by jamcnaughton** [comment]
This isn't in the scope of the paper - we're just looking at issues occurring from changing display shape - not adapting legacy software for use on touch screens.
